services:
  # Backend API Service
  - type: web
    name: moe-command-console-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install --production=false && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://moe-command-console-frontend.onrender.com
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Web Service
  - type: web
    name: moe-command-console-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://moe-command-console-backend.onrender.com
    autoDeploy: true 